CREATE TABLE IF NOT EXISTS guest (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(100) NOT NULL,
  text_message TEXT NOT NULL,
  e_mail VARCHAR(255) NOT NULL,
  data_time_message TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
