
services:
  db:
    image: mysql:8.0
    env_file:
      - .env       
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  
  app:
    build: .
    env_file:
      - .env
    volumes:                # mounts php
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db