version: "3.9"

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  migrator:
    image: mysql:8.0
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations:ro
    entrypoint: ["/bin/sh", "-c"]
    command: |
      set -e
      echo "Waiting for database to become ready..."
      until mysqladmin ping -h${DB_HOST} -u${DB_USER} -p${DB_PASS} --silent; do
        sleep 2
      done
      echo "Database is ready. Applying migrations..."
      for file in /migrations/*.sql; do
        echo "Running $file"
        mysql -h${DB_HOST} -u${DB_USER} -p${DB_PASS} ${DB_NAME} < "$file"
      done
      echo "Migrations applied."
    restart: "no"

  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
